export const appRoutes = {
  main: { link: "/", persianTitle: "شایان نگارش" },
  about: { link: "/about", persianTitle: "درباره ما" },
  contact: { link: "/contact", persianTitle: "ارتباط با ما" },
  brands: { link: "/brands", persianTitle: "برندها" },
  login: { link: "/signin", persianTitle: "ورود" },
  register: { link: "/signup", persianTitle: "عضویت" },
  profile: { link: "/profile", persianTitle: "حساب کاربری" },
  profileInfo: { link: "/profile/info", persianTitle: "اطلاعات حساب" },
  profileOrders: { link: "/profile/orders", persianTitle: "سفارش ها" },
  products: { link: "/products", persianTitle: "همه محصولات" },
  faq: { link: "/faq", persianTitle: "سوالات متداول" },
  orderGuid: { link: "/order-guide", persianTitle: "راهنمای سفارش" },
  order: { link: "/orders", persianTitle: "سفارش ها" },
  category: { link: "/category", persianTitle: "همه دسته ها" },
  categorySlug: { link: "/category/:slug" },
  subcategories: { link: "/subcategories", persianTitle: "همه زیر دسته ها" },
  tags: { link: "/tags", persianTitle: "برچسب ها" },
  cart: { link: "/cart", persianTitle: "سبد خرید" },
  payment: { link: "/pay", persianTitle: "پرداخت" },
  forgotPassword: {
    link: "/forgot-password",
    persianTitle: "فراموشی رمز عبور",
  },
};
