export const routes = {
  main: "/",
  about: "/about",
  contact: "/contact",
  brands: "/brands",
  login: "/signin",
  register: "/signup",
  profile: "/profile",
  profileInfo: "/profile/info",
  profileOrders: "/profile/orders",
  category: "/category",
  faq: "/faq",
  orderGuide: "/order-guide",
  products: "/products",
  tags: "/tags",
  cart: "/cart",
  forgotPassword: "/forgot-password",
};

export const routesPersianTitle = {
  main: "خانه",
  about: "درباره ما",
  contact: "ارتباط با ما",
  brands: "برندها",
  login: "ورود",
  register: "عضویت",
  profile: "پروفایل",
  profileInfo: "اطلاعات حساب",
  profileOrders: "سفارش ها",
  category: "زیر دسته ها",
  faq: "سوالات متداول",
  orderGuide: "/order-guide",
  products: "محصولات",
  tags: "برچسب ها",
  cart: "سبد خرید",
  forgotPassword: "فراموشی رمز عبور",
};

export const appRoutes = {
  main: { link: "/", persianTitle: "خانه" },
  about: { link: "/about", persianTitle: "درباره ما" },
  contact: { link: "/contact", persianTitle: "ارتباط با ما" },
  brands: { link: "/brands", persianTitle: "برندها" },
  login: { link: "/signin", persianTitle: "ورود" },
  register: { link: "/signup", persianTitle: "عضویت" },
  profile: { link: "/profile", persianTitle: "پروفایل" },
  profileInfo: { link: "/profile/info", persianTitle: "اطلاعات حساب" },
  profileOrders: { link: "/profile/orders", persianTitle: "سفارش ها" },
  products: { link: "/products", persianTitle: "همه محصولات" },
  faq: { link: "/faq", persianTitle: "سوالات متداول" },
  orderGuid: { link: "/order-guide", persianTitle: "سوالات متداول" },
  order: { link: "/orders", persianTitle: "سفارش ها" },
  category: { link: "/category", persianTitle: "زیر دسته ها" },
  tags: { link: "/tags", persianTitle: "برچسب ها" },
  cart: { link: "/cart", persianTitle: "سبد خرید" },
  payment: { link: "/pay", persianTitle: "پرداخت" },
  forgotPassword: {
    link: "/forgot-password",
    persianTitle: "فراموشی رمز عبور",
  },
};
